apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-microservice
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: sample-microservice
    spec:
      containers:
        - name: sample-microservice
          image: gcr.io/resonant-augury-288013/sample-microservice:20
          ports:
            - containerPort: 8080
          args:
            - 'image-pull-policy: Always'

---
apiVersion: v1
kind: Service
metadata:
  name: sample-microservice-service
  labels:
    name: sample-microservice-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: sample-microservice
  type: LoadBalancer